### ISSUE TITLE
code for extracting conversations

### ISSUE THREAD

**Issue by Anna146** [sarnthil/gutenberg-conversations#3]
Hi,

Can you maybe provide the code which creates the file "books.csv"?
Thanks!

Anna

**Comment by sarnthil** [comment]
Hi Anna,

I don't have that code anymore (it's been four years), but it shouldn't be too hard to recreate it using the Gutenberg API. In particular, I used the [gutenberg](https://pypi.org/project/Gutenberg/) Python package, which can translate an etext_id into the contents of the book (to get the title and other metadata, you can use `gutenberg.query.get_metadata`).
